-- liquibase formatted sql

-- changeset sokol:1
CREATE TABLE faculty (
    id BIGINT NOT NULL generated by default as identity PRIMARY KEY,
    faculty_name varchar(255) NOT NULL
);

-- changeset sokol:2
ALTER TABLE faculty ADD CONSTRAINT name_unique UNIQUE (faculty_name);