-- liquibase formatted sql

-- changeset sokol:1
CREATE TABLE method_execution_time_tracking (
    id BIGINT NOT NULL generated by default as identity PRIMARY KEY,
    method_name VARCHAR(255) NOT NULL,
    execution_time BIGINT
);