-- liquibase formatted sql

-- changeset sokol:1
CREATE TABLE student (
    id BIGINT NOT NULL generated by default as identity PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    age INTEGER NOT NULL,
    faculty_id BIGINT
);

-- changeset sokol:2
ALTER TABLE student ADD FOREIGN KEY (faculty_id) REFERENCES faculty;

--changeset sokol:3
ALTER TABLE student ADD CONSTRAINT age_constraint CHECK (age >= 16);